server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  security:
    user:
      name: guccin
      password: 123123

management:
  endpoints:
    web:
      exposure:
        include: "*"